"use client";

import { FormEvent, useEffect, useState } from "react";
import { Contact, Crown, Database, ImagePlus, Palette, Plus, Save, Settings2, Store, Trash2, UserCog } from "lucide-react";
import { ConfirmDialog, Modal, useFeedback } from "@/components/app-provider";
import { PageHeader } from "@/components/page-header";
import { Badge, Button, Field, Input, Select, Surface, Textarea } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";

type Section = "ข้อมูลร้าน" | "ช่องทางติดต่อ" | "กฎแต้ม" | "แรงค์สมาชิก" | "ธีมบัตร" | "บัญชีพนักงาน" | "ข้อมูลระบบ";
const sections: Array<{ name: Section; icon: typeof Store }> = [
  { name: "ข้อมูลร้าน", icon: Store }, { name: "ช่องทางติดต่อ", icon: Contact }, { name: "กฎแต้ม", icon: Settings2 }, { name: "แรงค์สมาชิก", icon: Crown }, { name: "ธีมบัตร", icon: Palette }, { name: "บัญชีพนักงาน", icon: UserCog }, { name: "ข้อมูลระบบ", icon: Database },
];

export default function SettingsPage() {
  const [section, setSection] = useState<Section>("ข้อมูลร้าน");
  return <div className="mx-auto max-w-7xl animate-rise"><PageHeader title="ตั้งค่าระบบ" description="ตั้งค่าร้านและระบบสมาชิกจากจุดเดียว" /><div className="grid gap-5 lg:grid-cols-[230px_minmax(0,1fr)]"><Surface className="h-fit p-2">{sections.map(({ name, icon: Icon }) => <button key={name} onClick={() => setSection(name)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-semibold ${section === name ? "bg-[var(--brand-50)] text-[var(--brand-600)]" : "text-stone-600 hover:bg-stone-50"}`}><Icon size={18} />{name}</button>)}</Surface><main><h2 className="mb-4 text-xl font-black">{section}</h2>{section === "ข้อมูลร้าน" ? <StorePanel /> : null}{section === "ช่องทางติดต่อ" ? <ContactPanel /> : null}{section === "กฎแต้ม" ? <PointRulePanel /> : null}{section === "แรงค์สมาชิก" ? <RankPanel /> : null}{section === "ธีมบัตร" ? <ThemePanel /> : null}{section === "บัญชีพนักงาน" ? <StaffPanel /> : null}{section === "ข้อมูลระบบ" ? <DataPanel /> : null}</main></div></div>;
}

function StorePanel() {
  const { notify } = useFeedback();
  const [data, setData] = useState({ store_name: "แทมมี่อาหารสัตว์", tagline: "ระบบสมาชิกและสะสมแต้ม", welcome_message: "ทุกการซื้อมีความหมาย", login_hero_url: "" });
  useEffect(() => { createClient().from("store_settings").select("store_name,tagline,welcome_message,login_hero_url").eq("id", true).single().then(({ data: row }) => { if (row) setData({ ...row, login_hero_url: row.login_hero_url ?? "" }); }); }, []);
  async function save() { const { error } = await createClient().from("store_settings").update(data).eq("id", true); notify(error ? "บันทึกข้อมูลร้านไม่สำเร็จ" : "บันทึกข้อมูลร้านแล้ว", error ? "info" : undefined); }
  async function upload(file?: File) { if (!file) return; const path = `store/${crypto.randomUUID()}.${file.name.split(".").pop()}`; const storage = createClient().storage.from("tammy-media"); const { error } = await storage.upload(path, file); if (error) { notify("อัปโหลดรูปไม่สำเร็จ", "info"); return; } setData((current) => ({ ...current, login_hero_url: storage.getPublicUrl(path).data.publicUrl })); }
  return <Surface className="space-y-4 p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="ชื่อร้าน"><Input value={data.store_name} onChange={(e) => setData({ ...data, store_name: e.target.value })} /></Field><Field label="คำอธิบายระบบ"><Input value={data.tagline} onChange={(e) => setData({ ...data, tagline: e.target.value })} /></Field></div><Field label="ข้อความต้อนรับ"><Textarea rows={3} value={data.welcome_message} onChange={(e) => setData({ ...data, welcome_message: e.target.value })} /></Field><div className="rounded-2xl border border-[var(--line)] p-4"><p className="text-sm font-bold">รูปหน้าเข้าสู่ระบบ</p>{data.login_hero_url ? <img src={data.login_hero_url} alt="รูปหน้าเข้าสู่ระบบ" className="mt-3 aspect-[16/9] max-w-md rounded-xl object-contain" /> : null}<label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><ImagePlus size={17} />{data.login_hero_url ? "เปลี่ยนรูป" : "เพิ่มรูป"}<input type="file" accept="image/*" className="sr-only" onChange={(e) => upload(e.target.files?.[0])} /></label></div><Button variant="primary" icon={<Save size={17} />} onClick={save}>บันทึกข้อมูลร้าน</Button></Surface>;
}

type Channel = { id: string; platform: string; label: string; url: string; is_active: boolean };
function ContactPanel() {
  const { notify } = useFeedback(); const [items, setItems] = useState<Channel[]>([]); const [open, setOpen] = useState(false);
  const load = () => createClient().from("contact_channels").select("id,platform,label,url,is_active").order("sort_order").then(({ data }) => setItems(data ?? []));
  useEffect(() => { load(); }, []);
  async function add(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = new FormData(e.currentTarget); const { error } = await createClient().from("contact_channels").insert({ platform: form.get("platform"), label: form.get("label"), url: form.get("url"), is_active: true, sort_order: items.length }); if (error) { notify("เพิ่มช่องทางไม่สำเร็จ", "info"); return; } setOpen(false); load(); notify("เพิ่มช่องทางติดต่อแล้ว"); }
  return <><Surface className="overflow-hidden"><div className="flex justify-end border-b p-4"><Button variant="primary" size="sm" icon={<Plus size={15} />} onClick={() => setOpen(true)}>เพิ่มช่องทาง</Button></div><div className="divide-y">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center gap-3 p-4"><div className="flex-1"><b>{item.platform}</b><p className="text-sm text-stone-500">{item.label}</p><a className="text-xs text-[var(--brand-600)]" href={item.url} target="_blank" rel="noreferrer">{item.url}</a></div><button onClick={async () => { await createClient().from("contact_channels").update({ is_active: !item.is_active }).eq("id", item.id); load(); }} className={`rounded-full px-3 py-1 text-xs font-bold text-white ${item.is_active ? "bg-emerald-500" : "bg-red-500"}`}>{item.is_active ? "เปิด" : "ปิด"}</button><Button size="sm" variant="danger" onClick={async () => { await createClient().from("contact_channels").delete().eq("id", item.id); load(); }}><Trash2 size={14} /></Button></div>)}</div></Surface><Modal open={open} onClose={() => setOpen(false)} title="เพิ่มช่องทางติดต่อร้าน"><form onSubmit={add} className="space-y-4"><Field label="แอปหรือแพลตฟอร์ม"><Select name="platform"><option>LINE</option><option>Facebook</option><option>Instagram</option><option>TikTok</option><option>เว็บไซต์</option></Select></Field><Field label="ชื่อที่แสดง"><Input name="label" required /></Field><Field label="ลิงก์"><Input name="url" type="url" placeholder="https://..." required /></Field><Button className="w-full" variant="primary" type="submit">บันทึกช่องทาง</Button></form></Modal></>;
}

function PointRulePanel() {
  const { notify } = useFeedback(); const [spend, setSpend] = useState(100); const [points, setPoints] = useState(1); const [expiry, setExpiry] = useState<string>("");
  useEffect(() => { createClient().from("store_settings").select("spend_per_unit,points_per_unit,points_expiry_months").eq("id", true).single().then(({ data }) => { if (data) { setSpend(Number(data.spend_per_unit)); setPoints(data.points_per_unit); setExpiry(data.points_expiry_months?.toString() ?? ""); } }); }, []);
  async function save() { const { error } = await createClient().from("store_settings").update({ spend_per_unit: spend, points_per_unit: points, points_expiry_months: expiry ? Number(expiry) : null }).eq("id", true); notify(error ? "บันทึกกฎแต้มไม่สำเร็จ" : "บันทึกกฎแต้มแล้ว และหน้าให้แต้มจะใช้ค่านี้ทันที", error ? "info" : undefined); }
  return <Surface className="p-5"><div className="grid gap-4 sm:grid-cols-3"><Field label="ยอดซื้อกี่บาท"><Input type="number" min="1" value={spend} onChange={(e) => setSpend(Number(e.target.value))} /></Field><Field label="เท่ากับกี่แต้ม"><Input type="number" min="1" value={points} onChange={(e) => setPoints(Number(e.target.value))} /></Field><Field label="อายุแต้ม"><Select value={expiry} onChange={(e) => setExpiry(e.target.value)}><option value="">ไม่มีวันหมดอายุ</option><option value="6">6 เดือน</option><option value="12">12 เดือน</option><option value="24">24 เดือน</option></Select></Field></div><div className="my-5 rounded-2xl bg-emerald-50 p-4 text-sm text-emerald-800"><b>ตัวอย่าง: {spend.toLocaleString()} บาท = {points.toLocaleString()} แต้ม</b><p className="mt-1">ยอดซื้อ 1,000 บาท จะได้รับ {Math.floor(1000 / Math.max(spend, 1)) * points} แต้ม</p></div><Button variant="primary" icon={<Save size={17} />} onClick={save}>บันทึกกฎแต้ม</Button></Surface>;
}

type Rank = { id: string; name: string; minimum_spend: number; color: string; sort_order: number };
function RankPanel() {
  const { notify } = useFeedback(); const [items, setItems] = useState<Rank[]>([]); const colors = ["#4d9b8d", "#9ca3af", "#e3a019", "#f05b51", "#7665a8", "#477dd1"];
  const load = () => createClient().from("ranks").select("id,name,minimum_spend,color,sort_order").order("sort_order").then(({ data }) => setItems((data as Rank[]) ?? [])); useEffect(() => { load(); }, []);
  async function save(rank: Rank) { const { error } = rank.id.startsWith("new-") ? await createClient().from("ranks").insert({ name: rank.name, minimum_spend: rank.minimum_spend, color: rank.color, sort_order: rank.sort_order }) : await createClient().from("ranks").update({ name: rank.name, minimum_spend: rank.minimum_spend, color: rank.color, sort_order: rank.sort_order }).eq("id", rank.id); if (error) { notify("บันทึกแรงค์ไม่สำเร็จ", "info"); return; } load(); notify("บันทึกแรงค์แล้ว"); }
  return <Surface className="overflow-hidden"><div className="flex justify-end border-b p-4"><Button size="sm" variant="primary" icon={<Plus size={15} />} onClick={() => setItems((current) => [...current, { id: `new-${Date.now()}`, name: "แรงค์ใหม่", minimum_spend: 0, color: colors[current.length % colors.length], sort_order: current.length }])}>เพิ่มแรงค์</Button></div><div className="divide-y">{items.map((rank) => <div key={rank.id} className="grid gap-3 p-4 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-end"><Field label="ชื่อแรงค์"><Input value={rank.name} onChange={(e) => setItems((current) => current.map((x) => x.id === rank.id ? { ...x, name: e.target.value } : x))} /></Field><Field label="ยอดซื้อขั้นต่ำ"><Input type="number" min="0" value={rank.minimum_spend} onChange={(e) => setItems((current) => current.map((x) => x.id === rank.id ? { ...x, minimum_spend: Number(e.target.value) } : x))} /></Field><div className="flex gap-1">{colors.map((color) => <button key={color} aria-label={`เลือกสี ${color}`} onClick={() => setItems((current) => current.map((x) => x.id === rank.id ? { ...x, color } : x))} className={`h-8 w-8 rounded-lg border-2 ${rank.color === color ? "border-stone-800" : "border-white"}`} style={{ backgroundColor: color }} />)}</div><Button size="sm" variant="primary" onClick={() => save(rank)}>บันทึก</Button></div>)}</div></Surface>;
}

function ThemePanel() { const { notify } = useFeedback(); const [items, setItems] = useState<Array<{ id: string; name: string; primary_color: string; secondary_color: string; is_active: boolean }>>([]); const load = () => createClient().from("card_themes").select("id,name,primary_color,secondary_color,is_active").order("sort_order").then(({ data }) => setItems(data ?? [])); useEffect(() => { load(); }, []); return <Surface className="grid gap-4 p-5 sm:grid-cols-2">{items.map((item) => <div key={item.id} className="rounded-2xl border p-4"><div className="h-24 rounded-xl" style={{ background: `linear-gradient(135deg, ${item.primary_color}, ${item.secondary_color})` }} /><div className="mt-3 flex items-center justify-between"><b>{item.name}</b><button onClick={async () => { await createClient().from("card_themes").update({ is_active: !item.is_active }).eq("id", item.id); load(); notify("อัปเดตธีมแล้ว"); }} className={`rounded-full px-3 py-1 text-xs font-bold text-white ${item.is_active ? "bg-emerald-500" : "bg-red-500"}`}>{item.is_active ? "เปิด" : "ปิด"}</button></div></div>)}</Surface>; }

function StaffPanel() { const [items, setItems] = useState<Array<{ user_id: string; display_name: string; username: string; role: string; is_active: boolean }>>([]); useEffect(() => { createClient().from("staff_profiles").select("user_id,display_name,username,role,is_active").then(({ data }) => setItems(data ?? [])); }, []); return <Surface className="divide-y">{items.map((item) => <div key={item.user_id} className="flex items-center gap-3 p-4"><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><UserCog size={18} /></span><div className="flex-1"><b>{item.display_name}</b><p className="text-sm text-stone-500">{item.username} · {item.role}</p></div><Badge tone={item.is_active ? "success" : "neutral"}>{item.is_active ? "ใช้งานอยู่" : "ระงับ"}</Badge></div>)}</Surface>; }

function DataPanel() { const { notify } = useFeedback(); const [confirm, setConfirm] = useState(false); async function exportCsv() { const { data } = await createClient().from("members").select("full_name,admin_alias,phone,total_spend,points_balance,created_at").order("created_at"); const rows = data ?? []; const csv = ["ชื่อ,ชื่อที่จำ,เบอร์โทร,ยอดซื้อ,แต้ม,วันที่สมัคร", ...rows.map((x) => [x.full_name, x.admin_alias ?? "", x.phone, x.total_spend, x.points_balance, x.created_at].map((v) => `"${String(v).replaceAll('"', '""')}"`).join(","))].join("\n"); const url = URL.createObjectURL(new Blob(["\ufeff", csv], { type: "text/csv;charset=utf-8" })); const a = document.createElement("a"); a.href = url; a.download = "tammy-members.csv"; a.click(); URL.revokeObjectURL(url); notify("ส่งออกข้อมูลสมาชิกแล้ว"); } return <><div className="grid gap-4 sm:grid-cols-2"><Surface className="p-5"><Database className="text-emerald-600" /><h3 className="mt-3 font-black">ส่งออกข้อมูล</h3><p className="mt-1 text-sm text-stone-500">ดาวน์โหลดสมาชิกจริงจากฐานข้อมูลเป็น CSV</p><Button className="mt-4" onClick={exportCsv}>ส่งออก CSV</Button></Surface><Surface className="border-red-100 p-5"><Trash2 className="text-red-500" /><h3 className="mt-3 font-black">ล้างข้อมูล</h3><p className="mt-1 text-sm text-stone-500">ฟังก์ชันอันตราย ต้องยืนยันก่อนใช้งาน</p><Button className="mt-4" variant="danger" onClick={() => setConfirm(true)}>ล้างข้อมูล</Button></Surface></div><ConfirmDialog open={confirm} title="ยังไม่เปิดใช้การล้างข้อมูล" description="เพื่อป้องกันข้อมูลจริง ระบบจะไม่ลบจนกว่าจะมีการยืนยันสิทธิ์ผู้ดูแลขั้นสูง" confirmLabel="รับทราบ" onClose={() => setConfirm(false)} onConfirm={() => setConfirm(false)} /></>; }
