"use client";
/* eslint-disable react-hooks/use-memo, react-hooks/set-state-in-effect */

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { Bell, CheckCircle2, Clock3, Crown, Gift, LockKeyhole, Palette, Save, ShieldCheck, Store, UserCog } from "lucide-react";
import { LoyaltyCard } from "@/components/loyalty-card";
import { PhonePreview, SettingRow, SettingsCard, Toggle } from "@/components/settings-ui";
import { Badge, Button, Field, Input, Select, Textarea, cn } from "@/components/ui";
import { useFeedback } from "@/components/app-provider";
import { defaultStoreBrand, useStoreBrand, type StoreBrand } from "@/components/store-brand-provider";
import { createClient } from "@/lib/supabase/client";
import { MemberSettingsPanel } from "@/components/member-settings-panel";
import { StoreSettingsPanel } from "@/components/store-settings-panel";
import { CardSettingsPanel } from "@/components/card-settings-panel";
import { ContentSettingsPanel } from "@/components/content-settings-panel";
import { TeamSettingsPanel } from "@/components/team-settings-panel";

type Tab = "store" | "members" | "card" | "content" | "security";
const tabs: Array<[Tab,string]> = [["store","ข้อมูลร้านและภาพลักษณ์"],["members","สมาชิก แต้ม และแรงค์"],["card","บัตรสมาชิกและมาสคอต"],["content","เนื้อหาและสิทธิพิเศษ"],["security","ทีมงานและสิทธิ์การใช้งาน"]];

export default function SettingsPage(){
  const[tab,setTab]=useState<Tab>("store");
  return <div className="mx-auto max-w-[1420px] animate-rise"><header className="mb-1 flex flex-wrap items-end gap-4 border-b border-stone-200 pb-5"><div className="min-w-0 flex-1"><h1 className="text-3xl font-black tracking-tight sm:text-4xl">ตั้งค่าระบบ</h1><p className="mt-1 text-sm text-stone-500">จัดการข้อมูลร้าน สมาชิก และสิทธิ์การใช้งาน</p></div><span className="inline-flex items-center gap-2 text-sm font-bold text-emerald-600"><span className="h-2.5 w-2.5 rounded-full bg-emerald-500"/>บันทึกแล้ว</span>{tab!=="store"&&tab!=="security"?<Button onClick={()=>document.querySelector(".settings-phone")?.scrollIntoView({behavior:"smooth",block:"center"})}>ดูตัวอย่าง</Button>:null}<Button variant="primary" icon={<Save size={17}/>} onClick={()=>document.querySelector<HTMLButtonElement>("[data-settings-save]")?.click()}>บันทึกการตั้งค่า</Button></header><nav className="settings-main-tabs soft-scroll">{tabs.map(([id,label])=><button type="button" key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav><div className="mt-4">{tab==="store"?<StoreSettingsPanel/>:tab==="members"?<MemberSettingsPanel/>:tab==="card"?<CardSettingsPanel/>:tab==="content"?<ContentSettingsPanel/>:<TeamSettingsPanel/>}</div></div>;
}

function StorePanel({onCard}:{onCard:()=>void}){
 const db=useMemo(createClient,[]);const{notify}=useFeedback();const{brand,refresh}=useStoreBrand();const[form,setForm]=useState<StoreBrand>(brand);useEffect(()=>setForm(brand),[brand]);const set=<K extends keyof StoreBrand>(k:K,v:StoreBrand[K])=>setForm(x=>({...x,[k]:v}));
 async function save(){const{error}=await db.from("store_settings").update({store_name:form.store_name,store_name_en:form.store_name_en,description:form.description,welcome_message:form.welcome_message,brand_primary:form.brand_primary,brand_secondary:form.brand_secondary,opening_hours:form.opening_hours}).eq("id",true);if(error)return notify("บันทึกไม่สำเร็จ","info");await refresh();notify("บันทึกข้อมูลร้านแล้ว");}
 return <div className="settings-layout"><div className="space-y-4"><SettingsCard title="โลโก้และข้อมูลร้าน"><div className="grid gap-6 lg:grid-cols-[190px_1fr]"><div className="relative mx-auto aspect-square w-40 overflow-hidden rounded-[28px] border bg-orange-50"><Image unoptimized src={form.logo_url||defaultStoreBrand.logo_url} alt="โลโก้ร้าน" fill sizes="160px" className="object-contain p-3"/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="ชื่อร้าน"><Input value={form.store_name} onChange={e=>set("store_name",e.target.value)}/></Field><Field label="ชื่อภาษาอังกฤษ"><Input value={form.store_name_en} onChange={e=>set("store_name_en",e.target.value)}/></Field><Field label="คำอธิบายร้าน"><Textarea rows={3} value={form.description} onChange={e=>set("description",e.target.value)}/></Field><Field label="ข้อความต้อนรับ"><Textarea rows={3} value={form.welcome_message} onChange={e=>set("welcome_message",e.target.value)}/></Field></div></div><div className="mt-5 border-t pt-5"><b>สีหลักของระบบผู้ใช้</b><div className="mt-3 flex flex-wrap gap-3"><Color value={form.brand_primary} onChange={v=>set("brand_primary",v)}/><Color value={form.brand_secondary} onChange={v=>set("brand_secondary",v)}/><Button icon={<Palette size={17}/>} onClick={onCard}>ตั้งค่าธีมบัตรและมาสคอต</Button></div></div></SettingsCard><SettingsCard title="เวลาเปิด–ปิดร้าน"><p className="text-sm text-stone-500">ตั้งค่าเวลาให้ลูกค้าเห็นในเมนูติดต่อร้าน</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="เวลาเปิด"><Input type="time" defaultValue="09:00"/></Field><Field label="เวลาปิด"><Input type="time" defaultValue="18:00"/></Field></div></SettingsCard><Button variant="primary" icon={<Save size={17}/>} onClick={save}>บันทึกข้อมูลร้าน</Button></div><PhonePreview title="ตัวอย่างหน้า Login บนมือถือ"><div className="p-5 text-center"><Image unoptimized src={form.logo_url||defaultStoreBrand.logo_url} alt="" width={90} height={90} className="mx-auto h-20 w-20 object-contain"/><h3 className="mt-2 font-black">{form.store_name}</h3><p className="mt-1 text-xs text-stone-500">{form.welcome_message}</p><div className="mt-5 space-y-2 text-left"><div className="control p-3 text-xs text-stone-400">เบอร์โทรศัพท์</div><div className="control p-3 text-xs text-stone-400">รหัสผ่าน</div><div className="rounded-xl p-3 text-center text-xs font-bold text-white" style={{background:form.brand_primary}}>เข้าสู่ระบบ</div></div></div></PhonePreview></div>;
}
function Color({value,onChange}:{value:string;onChange:(v:string)=>void}){return <label className="flex items-center gap-2 rounded-xl border bg-white p-2 pr-4 text-xs"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-9 w-10"/><span className="uppercase">{value}</span></label>}

type Rank={id:string;name:string;minimum_spend:number;color:string};
function MemberPanel(){const db=useMemo(createClient,[]);const{notify}=useFeedback();const[spend,setSpend]=useState(100);const[points,setPoints]=useState(1);const[expiry,setExpiry]=useState("");const[reset,setReset]=useState("");const[ranks,setRanks]=useState<Rank[]>([]);useEffect(()=>{void Promise.all([db.from("store_settings").select("spend_per_unit,points_per_unit,points_expiry_months,rank_reset_months").eq("id",true).single(),db.from("ranks").select("id,name,minimum_spend,color").order("sort_order")]).then(([s,r])=>{if(s.data){setSpend(Number(s.data.spend_per_unit));setPoints(s.data.points_per_unit);setExpiry(s.data.points_expiry_months?.toString()??"");setReset(s.data.rank_reset_months?.toString()??"")}setRanks((r.data as Rank[])??[])})},[]);async function save(){await db.from("store_settings").update({spend_per_unit:spend,points_per_unit:points,points_expiry_months:expiry?+expiry:null,rank_reset_months:reset?+reset:null}).eq("id",true);for(const r of ranks)await db.from("ranks").update({name:r.name,minimum_spend:r.minimum_spend,color:r.color}).eq("id",r.id);notify("บันทึกแต้มและแรงค์แล้ว")}
return <div className="settings-layout"><div className="space-y-4"><SettingsCard title="กฎการสะสมแต้ม"><div className="grid gap-4 sm:grid-cols-2"><Field label="ทุกยอดซื้อ (บาท)"><Input type="number" value={spend} onChange={e=>setSpend(+e.target.value)}/></Field><Field label="ได้รับ (แต้ม)"><Input type="number" value={points} onChange={e=>setPoints(+e.target.value)}/></Field><Field label="อายุแต้ม"><Select value={expiry} onChange={e=>setExpiry(e.target.value)}><option value="">ไม่มีวันหมดอายุ</option><option value="3">3 เดือน</option><option value="6">6 เดือน</option><option value="12">12 เดือน</option></Select></Field><Field label="รีแรงค์"><Select value={reset} onChange={e=>setReset(e.target.value)}><option value="">ไม่รีแรงค์</option><option value="3">ทุก 3 เดือน</option><option value="12">ทุกสิ้นปี</option></Select></Field></div></SettingsCard><SettingsCard title="แรงค์สมาชิก">{ranks.map(r=><div key={r.id} className="mb-2 grid gap-3 rounded-2xl border p-3 sm:grid-cols-[auto_1fr_180px]"><input type="color" value={r.color} onChange={e=>setRanks(x=>x.map(v=>v.id===r.id?{...v,color:e.target.value}:v))}/><Input value={r.name} onChange={e=>setRanks(x=>x.map(v=>v.id===r.id?{...v,name:e.target.value}:v))}/><Input aria-label="ยอดขั้นต่ำ" type="number" value={r.minimum_spend} onChange={e=>setRanks(x=>x.map(v=>v.id===r.id?{...v,minimum_spend:+e.target.value}:v))}/></div>)}</SettingsCard><Button variant="primary" icon={<Save size={17}/>} onClick={save}>บันทึกแต้มและแรงค์</Button></div><PhonePreview title="ตัวอย่างผลลัพธ์สำหรับสมาชิก"><div className="p-4"><LoyaltyCard points={2480} rank={ranks[1]?.name??"Gold"} nextRank={ranks[2]?.name??"Platinum"} nextAt={5000}/></div></PhonePreview></div>}

type Theme={id:string;name:string;primary_color:string;secondary_color:string;is_active:boolean};type Mascot={id:string;name:string;image_url:string;is_active:boolean};
function CardPanel(){const db=useMemo(createClient,[]);const{notify}=useFeedback();const[themes,setThemes]=useState<Theme[]>([]);const[mascots,setMascots]=useState<Mascot[]>([]);useEffect(()=>{void Promise.all([db.from("card_themes").select("id,name,primary_color,secondary_color,is_active").order("sort_order"),db.from("mascots").select("id,name,image_url,is_active").order("sort_order")]).then(([t,m])=>{setThemes((t.data as Theme[])??[]);setMascots((m.data as Mascot[])??[])})},[]);return <div className="settings-layout"><div className="space-y-4"><SettingsCard title="ธีมบัตรสมาชิก"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{themes.map(t=><div key={t.id} className="rounded-2xl border p-3"><div className="h-24 rounded-xl" style={{background:`linear-gradient(135deg,${t.primary_color},${t.secondary_color})`}}/><b className="mt-3 block text-sm">{t.name}</b><div className="mt-2 flex justify-between"><Badge tone={t.is_active?"success":"neutral"}>{t.is_active?"เปิด":"ปิด"}</Badge><Toggle label={t.name} checked={t.is_active} onChange={async v=>{await db.from("card_themes").update({is_active:v}).eq("id",t.id);setThemes(x=>x.map(y=>y.id===t.id?{...y,is_active:v}:y));notify("อัปเดตธีมแล้ว")}}/></div></div>)}</div></SettingsCard><SettingsCard title="มาสคอตจากร้าน"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{mascots.map(m=><div key={m.id} className="rounded-2xl border bg-orange-50 p-3"><div className="relative aspect-square"><Image unoptimized src={m.image_url} alt={m.name} fill sizes="140px" className="object-contain"/></div><b className="block truncate text-center text-xs">{m.name}</b></div>)}</div></SettingsCard></div><PhonePreview title="ตัวอย่างบัตรสมาชิก"><div className="p-4"><LoyaltyCard color={themes[0]?.primary_color} secondaryColor={themes[0]?.secondary_color} mascotUrl={mascots[0]?.image_url} points={2480} rank="Gold" nextRank="Platinum" nextAt={5000}/></div></PhonePreview></div>}

type Content={id:string;type:"news"|"reward";name:string;kind:string;enabled:boolean;order:number};
function ContentPanel(){const db=useMemo(createClient,[]);const{notify}=useFeedback();const[popup,setPopup]=useState(true);const[items,setItems]=useState<Content[]>([]);useEffect(()=>{void Promise.all([db.from("news_posts").select("id,title,show_after_login,popup_sort_order").eq("is_published",true),db.from("rewards").select("id,name,category,show_after_login,popup_sort_order").eq("is_active",true),db.from("store_settings").select("popup_enabled").eq("id",true).single()]).then(([n,r,s])=>{setPopup(s.data?.popup_enabled??true);setItems([...(n.data??[]).map(x=>({id:x.id,type:"news" as const,name:x.title,kind:"ข่าวสาร",enabled:x.show_after_login,order:x.popup_sort_order})),...(r.data??[]).map(x=>({id:x.id,type:"reward" as const,name:x.name,kind:x.category,enabled:x.show_after_login,order:x.popup_sort_order}))])})},[]);async function save(){await db.from("store_settings").update({popup_enabled:popup}).eq("id",true);for(const x of items)await db.from(x.type==="news"?"news_posts":"rewards").update({show_after_login:x.enabled,popup_sort_order:x.order}).eq("id",x.id);notify("บันทึกการแสดง Popup แล้ว")}
return <div className="settings-layout"><div className="space-y-4"><SettingsCard title="การแสดง Popup หลัง Login"><div className="mb-4 flex items-center gap-3"><Toggle label="เปิด Popup" checked={popup} onChange={setPopup}/><b className="text-sm">เปิด Popup โปรโมชั่น</b></div><div className="overflow-hidden rounded-2xl border">{items.map((x,i)=><div key={`${x.type}-${x.id}`} className="flex items-center gap-3 border-b p-3 last:border-0"><Badge tone={x.type==="news"?"brand":"success"}>{x.kind}</Badge><b className="min-w-0 flex-1 truncate text-sm">{x.name}</b><Toggle label={x.name} checked={x.enabled} onChange={v=>setItems(all=>all.map(y=>y.id===x.id&&y.type===x.type?{...y,enabled:v}:y))}/><span className="text-xs text-stone-400">{i+1}</span></div>)}</div></SettingsCard><SettingsCard title="การใช้สิทธิ์หน้าร้าน"><Field label="ข้อความสำหรับลูกค้า"><Textarea defaultValue="กรุณาใช้สิทธิ์ที่หน้าร้านและแสดงหน้านี้ให้พนักงาน" rows={3}/></Field></SettingsCard><Button variant="primary" icon={<Save size={17}/>} onClick={save}>บันทึกเนื้อหาและสิทธิพิเศษ</Button></div><PhonePreview title="ตัวอย่าง Popup สำหรับลูกค้า"><div className="m-4 mt-20 rounded-3xl bg-white p-5 text-center shadow-xl"><Gift className="mx-auto text-[var(--brand-600)]" size={56}/><h3 className="mt-4 text-xl font-black">{items.find(x=>x.enabled)?.name??"เลือกเนื้อหา Popup"}</h3><div className="mt-5 rounded-xl bg-[var(--brand-500)] p-3 text-xs font-bold text-white">ถัดไป</div><div className="mt-2 rounded-xl border p-3 text-xs">ปิด</div></div></PhonePreview></div>}

type Staff={user_id:string;display_name:string;username:string;role:string;is_active:boolean};
function SecurityPanel(){const db=useMemo(createClient,[]);const{notify}=useFeedback();const[staff,setStaff]=useState<Staff[]>([]);const[security,setSecurity]=useState({mfa_required:false,login_notifications:true,session_timeout_minutes:30});useEffect(()=>{void Promise.all([db.from("staff_profiles").select("user_id,display_name,username,role,is_active"),db.from("store_settings").select("mfa_required,login_notifications,session_timeout_minutes").eq("id",true).single()]).then(([a,b])=>{setStaff((a.data as Staff[])??[]);if(b.data)setSecurity(b.data)})},[]);async function save(){for(const s of staff)await db.from("staff_profiles").update({role:s.role,is_active:s.is_active}).eq("user_id",s.user_id);await db.from("store_settings").update(security).eq("id",true);notify("บันทึกทีมงานและความปลอดภัยแล้ว")}
return <div className="settings-layout"><div className="space-y-4"><SettingsCard title="บัญชีทีมงาน">{staff.map(s=><div key={s.user_id} className="flex flex-wrap items-center gap-3 border-b py-3 last:border-0"><span className="grid h-11 w-11 place-items-center rounded-full bg-orange-50"><UserCog size={18}/></span><div className="min-w-40 flex-1"><b className="text-sm">{s.display_name}</b><p className="text-xs text-stone-400">{s.username}</p></div><Select className="w-40" value={s.role} onChange={e=>setStaff(x=>x.map(y=>y.user_id===s.user_id?{...y,role:e.target.value}:y))}><option value="admin">ผู้ดูแลระบบ</option><option value="manager">ผู้จัดการร้าน</option><option value="staff">พนักงาน</option></Select><Toggle label={s.display_name} checked={s.is_active} onChange={v=>setStaff(x=>x.map(y=>y.user_id===s.user_id?{...y,is_active:v}:y))}/></div>)}</SettingsCard><SettingsCard title="สิทธิ์การใช้งานตามบทบาท"><div className="grid grid-cols-4 gap-2 text-center text-xs"><b className="text-left">เมนู</b><b>Admin</b><b>Manager</b><b>Staff</b>{["ให้แต้ม","สมาชิก","รางวัล","ตั้งค่า"].flatMap((x,i)=>[<span key={x} className="text-left">{x}</span>,...Array.from({length:3},(_,j)=><CheckCircle2 key={`${i}-${j}`} className={cn("mx-auto",j<=Math.max(0,2-i)?"text-emerald-500":"text-stone-200")} size={17}/>)])}</div></SettingsCard><Button variant="primary" icon={<Save size={17}/>} onClick={save}>บันทึกทีมงาน</Button></div><div className="space-y-4"><SettingsCard title="ความปลอดภัยของระบบ"><SettingRow icon={<ShieldCheck/>} title="ยืนยันตัวตนสองขั้นตอน"><Toggle label="MFA" checked={security.mfa_required} onChange={v=>setSecurity({...security,mfa_required:v})}/></SettingRow><SettingRow icon={<Bell/>} title="แจ้งเตือนการเข้าสู่ระบบใหม่"><Toggle label="แจ้งเตือน" checked={security.login_notifications} onChange={v=>setSecurity({...security,login_notifications:v})}/></SettingRow><SettingRow icon={<Clock3/>} title="ออกจากระบบเมื่อไม่ใช้งาน"><Select className="w-28" value={security.session_timeout_minutes} onChange={e=>setSecurity({...security,session_timeout_minutes:+e.target.value})}><option value={15}>15 นาที</option><option value={30}>30 นาที</option><option value={60}>60 นาที</option></Select></SettingRow></SettingsCard><SettingsCard title="ข้อมูลสมาชิกได้รับการปกป้อง" className="bg-emerald-50"><div className="flex gap-3 text-emerald-800"><LockKeyhole/><p className="text-sm">เปิดการจำกัดสิทธิ์ข้อมูลตามบัญชีผู้ใช้งานแล้ว</p></div></SettingsCard></div></div>}
