"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { ImagePlus, Link2, Plus, Save, Trash2 } from "lucide-react";
import { useFeedback } from "./app-provider";
import { SettingsCard, Toggle } from "./settings-ui";
import { useStoreBrand, type StoreBrand } from "./store-brand-provider";
import { Button, Field, Input, Select, Textarea } from "./ui";
import { uploadPublicImage } from "@/lib/image-upload";
import { createClient } from "@/lib/supabase/client";

type Channel = { id: string; platform: string; label: string; url: string; is_active: boolean; sort_order: number };
const days: Array<[string,string]> = [["mon","จันทร์"],["tue","อังคาร"],["wed","พุธ"],["thu","พฤหัสบดี"],["fri","ศุกร์"],["sat","เสาร์"],["sun","อาทิตย์"]];

export function StoreSettingsPanel() {
  const db = useMemo(() => createClient(), []); const { notify } = useFeedback(); const { brand, refresh } = useStoreBrand();
  const [form, setForm] = useState<StoreBrand>(brand); const [channels, setChannels] = useState<Channel[]>([]); const [busy, setBusy] = useState(false);
  useEffect(() => { queueMicrotask(() => setForm(brand)); }, [brand]);
  useEffect(() => { void db.from("contact_channels").select("id,platform,label,url,is_active,sort_order").order("sort_order").then(({ data }) => setChannels((data as Channel[]) ?? [])); }, [db]);
  const set = <K extends keyof StoreBrand>(key: K, value: StoreBrand[K]) => setForm(current => ({ ...current, [key]: value }));
  function setAllHours(part: "open" | "close", value: string) { set("opening_hours", Object.fromEntries(days.map(([key]) => [key, { ...(form.opening_hours[key] ?? { open: "09:00", close: "18:00", closed: false }), [part]: value, closed: false }]))); }

  async function upload(file: File | undefined, target: "logo_url" | "login_hero_url") { if (!file) return; setBusy(true); try { const url = await uploadPublicImage(db, file, target === "logo_url" ? "store/logo" : "store/login"); set(target, url); notify("อัปโหลดรูปแล้ว กดบันทึกเพื่อใช้งาน"); } catch (error) { notify(error instanceof Error ? error.message : "อัปโหลดรูปไม่สำเร็จ", "info"); } finally { setBusy(false); } }
  function changeChannel(id: string, patch: Partial<Channel>) { setChannels(items => items.map(item => item.id === id ? { ...item, ...patch } : item)); }
  function addChannel() { setChannels(items => [...items, { id: `new-${crypto.randomUUID()}`, platform: "LINE", label: "", url: "", is_active: true, sort_order: items.length }]); }
  async function removeChannel(item: Channel) { if (!item.id.startsWith("new-")) await db.from("contact_channels").delete().eq("id", item.id); setChannels(items => items.filter(value => value.id !== item.id)); }
  async function save() { setBusy(true); const { error } = await db.from("store_settings").update({ store_name: form.store_name, store_name_en: form.store_name_en || null, tagline: form.tagline, description: form.description, welcome_message: form.welcome_message, logo_url: form.logo_url, login_hero_url: form.login_hero_url, opening_hours: form.opening_hours }).eq("id", true); if (!error) for (const item of channels) { const value = { platform: item.platform, label: item.label, url: item.url, is_active: item.is_active, sort_order: item.sort_order }; if (item.id.startsWith("new-")) await db.from("contact_channels").insert(value); else await db.from("contact_channels").update(value).eq("id", item.id); } setBusy(false); if (error) return notify("บันทึกข้อมูลร้านไม่สำเร็จ", "info"); await refresh(); notify("บันทึกข้อมูลร้านและภาพลักษณ์แล้ว"); }

  return <div className="space-y-4">
    <div className="grid items-start gap-4 xl:grid-cols-[1.45fr_.95fr]">
      <SettingsCard title="โลโก้และข้อมูลร้าน"><div className="grid gap-6 md:grid-cols-[205px_1fr]"><div><div className="relative mx-auto aspect-square w-44 overflow-hidden rounded-[28px] bg-gradient-to-br from-orange-50 via-rose-50 to-white shadow-sm"><Image unoptimized src={form.logo_url} alt="โลโก้ร้าน" fill sizes="176px" className="object-contain p-4" /></div><UploadButton label="เปลี่ยนโลโก้" busy={busy} onFile={file => void upload(file, "logo_url")} /><p className="mt-2 text-center text-xs text-stone-400">JPG, JPEG, PNG, WEBP · บีบอัดไม่เกิน 5 MB</p></div><div className="grid content-start gap-4 sm:grid-cols-2"><Field label="ชื่อร้าน"><Input value={form.store_name} onChange={event => set("store_name", event.target.value)} /></Field><Field label="ชื่อภาษาอังกฤษ (ไม่บังคับ)"><Input value={form.store_name_en} onChange={event => set("store_name_en", event.target.value)} /></Field><Field label="คำอธิบายร้าน"><Textarea rows={3} value={form.description} onChange={event => set("description", event.target.value)} /></Field><Field label="ข้อความต้อนรับ"><Textarea rows={3} value={form.welcome_message} onChange={event => set("welcome_message", event.target.value)} /></Field></div></div></SettingsCard>
      <SettingsCard title="ช่องทางติดต่อร้าน" description="แก้ไข เพิ่ม และเลือกช่องทางที่ลูกค้าจะเห็น"><div className="space-y-3">{channels.map((item, index) => <div key={item.id} className="rounded-2xl border bg-stone-50/50 p-3"><div className="flex items-center gap-2"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-[var(--brand-600)] shadow-sm"><Link2 size={17} /></span><Select aria-label={`แพลตฟอร์ม ${index + 1}`} value={item.platform} onChange={event => changeChannel(item.id, { platform: event.target.value })}><option>LINE</option><option>Facebook</option><option>Instagram</option><option>TikTok</option><option>โทรศัพท์</option><option>เว็บไซต์</option></Select><Toggle label={`เปิด ${item.platform}`} checked={item.is_active} onChange={value => changeChannel(item.id, { is_active: value })} /><button type="button" aria-label={`ลบ ${item.platform}`} onClick={() => void removeChannel(item)} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-stone-400 hover:bg-red-50 hover:text-red-500"><Trash2 size={16} /></button></div><div className="mt-2 grid gap-2"><Input aria-label="ชื่อที่แสดง" placeholder="ชื่อที่แสดง" value={item.label} onChange={event => changeChannel(item.id, { label: event.target.value })} /><Input aria-label="ลิงก์หรือเบอร์โทร" placeholder="ลิงก์หรือเบอร์โทร" value={item.url} onChange={event => changeChannel(item.id, { url: event.target.value })} /></div></div>)}</div><Button className="mt-4 w-full" icon={<Plus size={16} />} onClick={addChannel}>เพิ่มช่องทางติดต่อ</Button></SettingsCard>
    </div>
    <div className="grid items-start gap-4 xl:grid-cols-[1.45fr_.95fr]">
      <SettingsCard title="รูปภาพหน้า Login" description="เปลี่ยนภาพได้อิสระ ระบบครอบภาพและบีบอัดให้อัตโนมัติ"><div className="grid gap-4 md:grid-cols-[1.4fr_1fr]"><div className="relative aspect-video overflow-hidden rounded-2xl border bg-stone-100">{form.login_hero_url ? <Image unoptimized src={form.login_hero_url} alt="รูปหน้า Login" fill sizes="700px" className="object-cover" /> : null}</div><UploadButton label="เปลี่ยนรูปหน้า Login" busy={busy} large onFile={file => void upload(file, "login_hero_url")} /></div></SettingsCard>
      <SettingsCard title="เวลาเปิด–ปิดร้าน" description="ตั้งครั้งเดียวและใช้เวลาเดียวกันทุกวัน"><div className="rounded-[24px] bg-gradient-to-br from-orange-50 via-rose-50/60 to-white p-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="เวลาเปิดร้าน"><Input type="time" value={form.opening_hours.mon?.open ?? "09:00"} onChange={event => setAllHours("open", event.target.value)} /></Field><Field label="เวลาปิดร้าน"><Input type="time" value={form.opening_hours.mon?.close ?? "18:00"} onChange={event => setAllHours("close", event.target.value)} /></Field></div><p className="mt-4 text-xs text-stone-500">เวลานี้จะแสดงในหน้าติดต่อร้านของลูกค้า</p></div></SettingsCard>
    </div>
    <div className="sticky bottom-4 z-10 flex justify-end"><Button data-settings-save variant="primary" icon={<Save size={18} />} disabled={busy} onClick={save}>{busy ? "กำลังบันทึก..." : "บันทึกข้อมูลร้าน"}</Button></div>
  </div>;
}

function UploadButton({ label, busy, large = false, onFile }: { label: string; busy: boolean; large?: boolean; onFile: (file?: File) => void }) { return <label className={large ? "grid min-h-40 cursor-pointer place-items-center rounded-2xl border-2 border-dashed border-[var(--brand-200)] bg-[var(--brand-50)]/40 text-center" : "mt-3 flex min-h-11 cursor-pointer items-center justify-center gap-2 rounded-xl border border-[var(--brand-500)] text-sm font-bold text-[var(--brand-600)]"}><span><ImagePlus className={large ? "mx-auto mb-2" : "mr-2 inline"} size={large ? 26 : 17} />{label}{large ? <small className="mt-1 block text-stone-400">JPG, PNG, WEBP · ไม่เกิน 5 MB</small> : null}</span><input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event => onFile(event.target.files?.[0])} /></label>; }
