"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { CalendarDays, Cat, ChevronRight, Dog, Gift, Home, LockKeyhole, Mail, Palette, Phone, Star, UserRound } from "lucide-react";
import { CatMark } from "@/components/brand";
import { CardCustomizer } from "@/components/card-customizer";
import { LoyaltyCard } from "@/components/loyalty-card";
import { ConfirmDialog, Modal, useFeedback } from "@/components/app-provider";
import { Badge, Button, Field, Input } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";

type PageName = "หน้าหลัก" | "แต้ม" | "แลกรางวัล" | "บัญชี" | "ตกแต่งบัตร";
type Reward = { id: string; name: string; description: string; points_cost: number; category: string; content_category?: string | null; image_url: string | null; stock?: number | null; conditions?: string; display_start?: string | null; display_end?: string | null; show_after_login?: boolean; popup_sort_order?: number };
type News = { id: string; title: string; excerpt: string; image_url: string | null; show_after_login?: boolean; popup_sort_order?: number };
type Theme = { id: string; name: string; primary_color: string; secondary_color: string };
type PointHistory = { id: string; label: string; value: number; createdAt: string };
type Profile = { fullName: string; birthDate: string; contactEmail: string };
const fallbackRewards: Reward[] = [{ id: "1", name: "ขนมแมวเลีย 4 ชิ้น", description: "คละรส", points_cost: 500, category: "อาหาร", image_url: null }, { id: "2", name: "ชามอาหารสแตนเลส", description: "1 ใบ", points_cost: 400, category: "ของใช้", image_url: null }, { id: "3", name: "ไม้ตกแมว", description: "คละสี", points_cost: 600, category: "ของเล่น", image_url: null }];
const fallbackNews: News[] = [{ id: "1", title: "โปรพิเศษประจำเดือน", excerpt: "ลดสูงสุด 20%", image_url: null }, { id: "2", title: "สมาชิก Gold", excerpt: "รับแต้ม 2 เท่า", image_url: null }, { id: "3", title: "สินค้าใหม่", excerpt: "สำหรับน้องแมว", image_url: null }];
const baseColors = ["#ef4d43", "#f58a44", "#4d9b8d", "#7665a8", "#ed7194", "#477dd1"];

export default function CustomerPage() {
  const router = useRouter(); const { notify } = useFeedback();
  const [page, setPage] = useState<PageName>("หน้าหลัก"); const [points, setPoints] = useState(0); const [memberName, setMemberName] = useState("สมาชิก"); const [memberPhone, setMemberPhone] = useState(""); const [color, setColor] = useState(baseColors[0]); const [secondaryColor, setSecondaryColor] = useState("#ffd189"); const [dogCount, setDogCount] = useState(0); const [catCount, setCatCount] = useState(0);
  const [rewards, setRewards] = useState<Reward[]>(fallbackRewards); const [news, setNews] = useState<News[]>(fallbackNews); const [themes, setThemes] = useState<Theme[]>([]); const [memberRank, setMemberRank] = useState("Member"); const [pointHistory, setPointHistory] = useState<PointHistory[]>([]); const [reward, setReward] = useState<Reward | null>(null); const [detailReward, setDetailReward] = useState<Reward | null>(null); const [modal, setModal] = useState<"notifications" | "news" | "pets" | "password" | "profile" | null>(null); const [popupNews, setPopupNews] = useState<News[]>([]); const [popupIndex, setPopupIndex] = useState(0); const [cardExtras, setCardExtras] = useState<{themeId?:string;mascotId?:string;mascotUrl?:string;patternId?:string;patternKey?:string;patternUrl?:string|null}>({ patternKey: "paws" });
  const [newPassword, setNewPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [passwordSaving, setPasswordSaving] = useState(false);
  const [memberId, setMemberId] = useState(""); const [profileSaving, setProfileSaving] = useState(false); const [profile, setProfile] = useState<Profile>({ fullName: "", birthDate: "", contactEmail: "" });
  const [popupRewards, setPopupRewards] = useState<News[]>([]); const [popupSuppressed, setPopupSuppressed] = useState(false);
  const [redeeming, setRedeeming] = useState(false);
  useEffect(() => { const supabase = createClient(); Promise.all([supabase.from("rewards").select("id,name,description,points_cost,category,content_category,image_url,stock,conditions,display_start,display_end").eq("is_active", true), supabase.from("news_posts").select("id,title,excerpt,image_url,show_after_login,popup_sort_order").eq("is_published", true).order("publish_at", { ascending: false }), supabase.from("card_themes").select("id,name,primary_color,secondary_color").eq("is_active", true).order("sort_order"), supabase.auth.getUser()]).then(async ([rewardsResult, newsResult, themesResult, userResult]) => { const loadedNews = (newsResult.data ?? []) as News[]; if (rewardsResult.data) setRewards(rewardsResult.data as Reward[]); if (newsResult.data) setNews(loadedNews); if (themesResult.data?.length) setThemes(themesResult.data as Theme[]); const user = userResult.data.user; if (!user) return; const selectedForPopup = loadedNews.filter((item) => item.show_after_login).sort((a, b) => (a.popup_sort_order ?? 0) - (b.popup_sort_order ?? 0)); if (selectedForPopup.length) { setPopupNews(selectedForPopup); setPopupIndex(0); } const style = user.user_metadata?.card_style; if (style && /^#[0-9a-f]{6}$/i.test(style.start) && /^#[0-9a-f]{6}$/i.test(style.end)) { setColor(style.start); setSecondaryColor(style.end); } const { data: member } = await supabase.from("members").select("id,full_name,phone,points_balance,total_spend,created_at,dog_count,cat_count,ranks(name)").eq("auth_user_id", user.id).maybeSingle(); if (member) { const balance = Number(member.points_balance ?? 0); const totalSpend = Number(member.total_spend ?? 0); setMemberName(member.full_name); setMemberPhone(member.phone); setPoints(balance); setDogCount(member.dog_count); setCatCount(member.cat_count); setMemberRank((member.ranks as unknown as { name?: string } | null)?.name ?? "Member"); if (balance === 0 && totalSpend === 0) { setPointHistory([]); return; } const { data: historyRows } = await supabase.from("point_transactions").select("*").eq("member_id", member.id).gte("created_at", member.created_at).order("created_at", { ascending: false }).limit(50); setPointHistory((historyRows ?? []).map((row) => normalizePointHistory(row as Record<string, unknown>))); } }); }, []);
  useEffect(() => { void createClient().auth.getUser().then(({data}) => { const style = data.user?.user_metadata?.card_style; if (style) setCardExtras({ themeId: style.themeId, mascotId: style.mascotId, mascotUrl: style.mascotUrl, patternId: style.patternId, patternKey: style.patternKey ?? "paws", patternUrl: style.patternUrl }); }); }, []);
  useEffect(() => {
    const db = createClient();
    void db.auth.getUser().then(async ({ data }) => {
      const user = data.user;
      if (!user) return;
      const metadata = user.user_metadata ?? {};
      const { data: member } = await db.from("members").select("id,full_name").eq("auth_user_id", user.id).maybeSingle();
      setMemberId(member?.id ?? "");
      setProfile({
        fullName: String(member?.full_name ?? metadata.full_name ?? ""),
        birthDate: String(metadata.birth_date ?? ""),
        contactEmail: String(metadata.contact_email ?? ""),
      });
    });
  }, []);
  useEffect(() => {
    const db = createClient();
    void db.auth.getUser().then(async ({ data }) => {
      if (!data.user) return;
      const today = localDateKey();
      if (localStorage.getItem(`tammy-popup-snooze:${data.user.id}`) === today) { setPopupSuppressed(true); return; }
      const { data: rows } = await db.from("rewards").select("id,name,description,image_url,show_after_login,popup_sort_order").eq("is_active", true).eq("show_after_login", true).order("popup_sort_order");
      setPopupRewards((rows ?? []).map((item) => ({ id: `reward-${item.id}`, title: item.name, excerpt: item.description, image_url: item.image_url, show_after_login: item.show_after_login, popup_sort_order: item.popup_sort_order })));
    });
  }, []);
  const popupItems = [...popupNews, ...popupRewards].sort((a, b) => (a.popup_sort_order ?? 0) - (b.popup_sort_order ?? 0));
  const coupons = rewards.filter((item) => item.category === "คูปอง");
  const redeemableRewards = rewards.filter((item) => item.category !== "คูปอง");
  const navItems = [[Home, "หน้าหลัก"], [Gift, "แลกรางวัล"], [UserRound, "บัญชี"]] as const;
  function changePage(next: PageName) { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function saveProfile() {
    if (!profile.fullName.trim()) return notify("กรุณากรอกชื่อ–นามสกุล", "info");
    if (profile.contactEmail && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(profile.contactEmail)) return notify("รูปแบบอีเมลไม่ถูกต้อง", "info");
    if (!memberId) return notify("ไม่พบข้อมูลสมาชิก กรุณาเข้าสู่ระบบอีกครั้ง", "info");
    setProfileSaving(true);
    const db = createClient();
    const [memberResult, authResult] = await Promise.all([
      db.from("members").update({ full_name: profile.fullName.trim(), dog_count: dogCount, cat_count: catCount }).eq("id", memberId),
      db.auth.updateUser({ data: { full_name: profile.fullName.trim(), birth_date: profile.birthDate || null, contact_email: profile.contactEmail.trim() || null } }),
    ]);
    setProfileSaving(false);
    if (memberResult.error || authResult.error) return notify(memberResult.error?.message ?? authResult.error?.message ?? "บันทึกข้อมูลไม่สำเร็จ", "info");
    setMemberName(profile.fullName.trim()); setModal(null); notify("บันทึกข้อมูลส่วนตัวแล้ว");
  }
  async function redeemSelectedReward() {
    if (!reward || redeeming) return;
    if (!memberId) return notify("ไม่พบข้อมูลสมาชิก กรุณาเข้าสู่ระบบอีกครั้ง", "info");
    if (points < reward.points_cost) return notify("แต้มไม่เพียงพอ", "info");
    setRedeeming(true);
    const db = createClient();
    const previousPoints = points;
    const nextPoints = previousPoints - reward.points_cost;
    const { data: updated, error: updateError } = await db.from("members").update({ points_balance: nextPoints }).eq("id", memberId).eq("points_balance", previousPoints).select("id").maybeSingle();
    if (updateError || !updated) { setRedeeming(false); return notify("ยอดแต้มมีการเปลี่ยนแปลง กรุณาโหลดหน้าแล้วลองใหม่", "info"); }
    const transaction = { member_id: memberId, points_delta: -reward.points_cost, transaction_type: "redeem", description: `แลก ${reward.name}` };
    const { data: historyRow, error: historyError } = await db.from("point_transactions").insert(transaction).select("*").single();
    if (historyError) {
      await db.from("members").update({ points_balance: previousPoints }).eq("id", memberId).eq("points_balance", nextPoints);
      setRedeeming(false);
      return notify("บันทึกประวัติการใช้แต้มไม่สำเร็จ ระบบคืนแต้มให้แล้ว", "info");
    }
    setPoints(nextPoints); setPointHistory((current) => [normalizePointHistory(historyRow as Record<string, unknown>), ...current]); setReward(null); setRedeeming(false); notify("แลกรางวัลสำเร็จและบันทึกประวัติแล้ว");
  }
  return <main className="min-h-screen bg-[var(--canvas)] sm:p-6"><div className="mx-auto min-h-screen max-w-md overflow-hidden customer-shell shadow-[var(--shadow-lg)] sm:min-h-[860px] sm:rounded-[32px] sm:border sm:border-[var(--line)]">
    <header className="sticky top-0 z-20 flex items-center justify-between border-b border-[var(--line)] bg-[#fffaf5]/95 px-5 py-4 backdrop-blur"><span className="font-black text-[var(--brand-600)]">🐾 Tammy <small className="font-normal text-stone-500">pet shop</small></span><span className="text-xs text-stone-500">สมาชิกและสะสมแต้ม</span></header>
    <div className="px-5 pb-28 pt-5">
      {page === "หน้าหลัก" ? <><p className="mb-3 text-stone-600">สวัสดี <b className="text-stone-900">{memberName}</b></p><LoyaltyCard color={color} secondaryColor={secondaryColor} points={points} rank={memberRank} memberName={memberName} mascotUrl={cardExtras.mascotUrl} patternKey={cardExtras.patternKey} patternUrl={cardExtras.patternUrl} /><Section title="ข่าวสาร" onAll={() => setModal("news")}><div className="flex gap-3 overflow-x-auto pb-2 soft-scroll">{news.slice(0, 3).map((item, index) => <Promo key={item.id} item={item} tone={index} />)}</div></Section>{coupons.length ? <Section title="คูปองสำหรับคุณ" onAll={() => changePage("แลกรางวัล")}><div className="grid grid-cols-2 gap-3">{coupons.slice(0, 2).map((item, index) => <RewardCard key={item.id} item={item} index={index} onOpen={() => setDetailReward(item)} />)}</div></Section> : null}<Section title="ของรางวัลแนะนำ" onAll={() => changePage("แลกรางวัล")}><div className="grid grid-cols-2 gap-3">{redeemableRewards.slice(0, 2).map((item, index) => <RewardCard key={item.id} item={item} index={index} onOpen={() => setDetailReward(item)} />)}</div></Section></> : null}
      {page === "แต้ม" ? <><PageTitle title="แต้มของฉัน" /><div className="surface mt-4 p-5"><p className="text-sm text-stone-500">แต้มคงเหลือ</p><b className="mt-1 block text-4xl tracking-tight">{points.toLocaleString()} <small className="text-sm">แต้ม</small></b><div className="mt-5 border-t border-[var(--line)] pt-4"><div className="flex justify-between"><b>{memberRank}</b><span className="text-xs text-stone-400">อีก {Math.max(0, 3000 - points)} แต้ม</span></div><div className="mt-3 h-2 rounded-full bg-stone-100"><div className="h-full rounded-full bg-amber-400" style={{ width: `${Math.min(100, points / 30)}%` }} /></div></div></div><h2 className="mt-7 font-black">ประวัติแต้ม</h2>{pointHistory.length ? <div className="mt-3 space-y-2">{pointHistory.map((item) => <div key={item.id} className="surface flex items-center p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${item.value >= 0 ? "bg-emerald-50 text-emerald-600" : "bg-red-50 text-red-500"}`}><Star size={18} /></span><span className="ml-3 flex-1"><b className="block text-sm">{item.label}</b><small className="text-stone-400">{new Date(item.createdAt).toLocaleString("th-TH", { dateStyle: "medium", timeStyle: "short" })}</small></span><b className={item.value >= 0 ? "text-emerald-600" : "text-red-500"}>{item.value >= 0 ? "+" : ""}{item.value.toLocaleString()}</b></div>)}</div> : <div className="mt-3 rounded-2xl border border-dashed border-stone-200 bg-white/60 px-5 py-10 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-stone-100 text-stone-400"><Star size={21}/></span><b className="mt-3 block text-sm">ยังไม่มีประวัติแต้ม</b><p className="mt-1 text-xs text-stone-400">เมื่อได้รับหรือใช้แต้ม รายการจะแสดงที่นี่</p></div>}</> : null}
      {page === "แลกรางวัล" ? <><PageTitle title="สิทธิพิเศษ" subtitle={`คุณมี ${points.toLocaleString()} แต้ม`} />{coupons.length ? <><h2 className="mt-5 font-black">คูปอง</h2><div className="mt-3 grid grid-cols-2 gap-3">{coupons.map((item, index) => <RewardCard key={item.id} item={item} index={index} onOpen={() => setDetailReward(item)} />)}</div></> : null}<h2 className="mt-6 font-black">ของรางวัล</h2><div className="mt-3 grid grid-cols-2 gap-3">{redeemableRewards.map((item, index) => <RewardCard key={item.id} item={item} index={index} onOpen={() => setDetailReward(item)} />)}</div></> : null}
      {page === "บัญชี" ? <><PageTitle title="บัญชีของฉัน" /><div className="surface mt-4 flex items-center p-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-stone-100"><UserRound /></span><div className="ml-3"><b>{memberName}</b><p className="text-xs text-stone-400">{memberPhone || "ยังไม่ได้เข้าสู่ระบบ"}</p></div><Badge className="ml-auto">{memberRank}</Badge></div><button type="button" onClick={() => changePage("ตกแต่งบัตร")} className="surface mt-4 flex w-full items-center p-4 text-left hover:border-[var(--brand-300)]"><Palette className="text-[var(--brand-600)]" /><span className="ml-3 flex-1 font-semibold">ตกแต่งบัตรสมาชิก</span><ChevronRight /></button><div className="surface mt-3 divide-y divide-[var(--line)]"><AccountButton icon={<UserRound size={18} />} label="ข้อมูลบัญชี" onClick={() => setModal("profile")} /><AccountButton icon={<Dog size={18} />} label={`สัตว์เลี้ยง: สุนัข ${dogCount} · แมว ${catCount}`} onClick={() => setModal("pets")} /><AccountButton icon={<Star size={18} />} label="ประวัติแต้ม" onClick={() => changePage("แต้ม")} /><AccountButton icon={<LockKeyhole size={18} />} label="เปลี่ยนรหัสผ่าน" onClick={() => setModal("password")} /><AccountButton icon={<ChevronRight size={18} />} label="ออกจากระบบ" danger onClick={async () => { await createClient().auth.signOut(); router.push("/login"); }} /></div></> : null}
      {page === "ตกแต่งบัตร" ? <CardCustomizer points={points} name={memberName} style={{start:color,end:secondaryColor,...cardExtras}} onCancel={()=>changePage("บัญชี")} onSave={async(style)=>{ const {error}=await createClient().auth.updateUser({data:{card_style:style}}); if(error){notify("บันทึกไม่สำเร็จ กรุณาลองใหม่","info");return;} setColor(style.start);setSecondaryColor(style.end);setCardExtras({themeId:style.themeId,mascotId:style.mascotId,mascotUrl:style.mascotUrl,patternId:style.patternId,patternKey:style.patternKey,patternUrl:style.patternUrl});notify("บันทึกการตกแต่งบัตรแล้ว");changePage("บัญชี"); }}/> : null}
    </div>
    <nav className="fixed bottom-0 left-1/2 z-20 grid w-full max-w-md -translate-x-1/2 grid-cols-3 border-t border-[var(--line)] bg-white/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] backdrop-blur sm:bottom-6 sm:rounded-b-[32px]">{navItems.map(([Icon, name]) => <button type="button" key={name} onClick={() => changePage(name)} className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-semibold ${page === name || (page === "ตกแต่งบัตร" && name === "บัญชี") ? "text-[var(--brand-600)]" : "text-stone-400 hover:bg-stone-50"}`}><Icon size={22} />{name === "หน้าหลัก" ? "บัตรของฉัน" : name === "แลกรางวัล" ? "สิทธิพิเศษ" : name}</button>)}</nav>
  </div>
  <Modal open={modal === "notifications"} onClose={() => setModal(null)} title="การแจ้งเตือน"><div className="space-y-2">{["คุณได้รับ 12 แต้มจากยอดซื้อล่าสุด", "Gold รับแต้ม 2 เท่าสัปดาห์นี้", "มีของรางวัลใหม่ให้แลก"].map((item) => <div key={item} className="rounded-xl bg-stone-50 p-3 text-sm">{item}</div>)}</div></Modal>
  {!popupSuppressed && popupItems.length ? <LoginPromoCarousel items={popupItems} index={Math.min(popupIndex, popupItems.length - 1)} onClose={(snoozeToday) => { if (snoozeToday) void createClient().auth.getUser().then(({ data }) => { if (data.user) localStorage.setItem(`tammy-popup-snooze:${data.user.id}`, localDateKey()); }); setPopupNews([]); setPopupRewards([]); }} onPrevious={() => setPopupIndex((value) => Math.max(0, value - 1))} onNext={() => setPopupIndex((value) => value === popupItems.length - 1 ? value : value + 1)} onDetails={() => { setPopupNews([]); setPopupRewards([]); setModal("news"); }} /> : null}
  <Modal open={modal === "news"} onClose={() => setModal(null)} title="ข่าวสารทั้งหมด"><div className="space-y-3">{news.map((item) => <div key={item.id} className="overflow-hidden rounded-2xl border border-[var(--line)]">{item.image_url ? <div className="relative aspect-square w-full bg-stone-50"><Image unoptimized src={item.image_url} alt={item.title} fill sizes="(max-width: 640px) 90vw, 460px" className="object-contain" /></div> : null}<div className="p-4"><b>{item.title}</b><p className="mt-1 text-sm text-stone-500">{item.excerpt}</p></div></div>)}</div></Modal>
  <Modal open={Boolean(detailReward)} onClose={() => setDetailReward(null)} title="รายละเอียดสิทธิพิเศษ" size="sm">{detailReward ? <RewardDetail item={detailReward} points={points} onRedeem={() => { setReward(detailReward); setDetailReward(null); }} /> : null}</Modal>
  <Modal open={modal === "profile"} onClose={() => setModal(null)} title="ข้อมูลส่วนตัว" description="ข้อมูลนี้ช่วยให้ร้านดูแลสมาชิกได้เหมาะสมยิ่งขึ้น"><div className="space-y-4"><Field label="ชื่อ–นามสกุล"><Input value={profile.fullName} onChange={(event) => setProfile({ ...profile, fullName: event.target.value })} autoComplete="name"/></Field><Field label="เบอร์โทรศัพท์" hint="ใช้สำหรับเข้าสู่ระบบ หากต้องการเปลี่ยนกรุณาติดต่อร้าน"><div className="control flex items-center gap-2 bg-stone-50 px-3 text-sm text-stone-600"><Phone size={16}/>{memberPhone || "ยังไม่มีข้อมูล"}</div></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="วันเกิด"><Input type="date" value={profile.birthDate} onChange={(event) => setProfile({ ...profile, birthDate: event.target.value })}/></Field><Field label="อีเมล"><div className="relative"><Mail className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={16}/><Input type="email" className="pl-10" value={profile.contactEmail} onChange={(event) => setProfile({ ...profile, contactEmail: event.target.value })} placeholder="name@example.com" autoComplete="email"/></div></Field></div><div className="rounded-2xl border border-stone-200 p-4"><b className="text-sm">ข้อมูลสัตว์เลี้ยง</b><p className="mt-1 text-xs text-stone-400">ระบุจำนวนสัตว์เลี้ยงเพื่อรับข่าวสารที่ตรงความสนใจ</p><PetCounter icon={<Dog />} label="สุนัข" value={dogCount} onChange={setDogCount}/><PetCounter icon={<Cat />} label="แมว" value={catCount} onChange={setCatCount}/></div><Button className="w-full" variant="primary" disabled={profileSaving} onClick={saveProfile}>{profileSaving ? "กำลังบันทึก..." : "บันทึกข้อมูลส่วนตัว"}</Button></div></Modal>
  <Modal open={modal === "pets"} onClose={() => setModal(null)} title="จำนวนสัตว์เลี้ยง"><PetCounter icon={<Dog />} label="สุนัข" value={dogCount} onChange={setDogCount} /><PetCounter icon={<Cat />} label="แมว" value={catCount} onChange={setCatCount} /><Button className="mt-5 w-full" variant="primary" onClick={async () => { if (!memberId) return notify("ไม่พบข้อมูลสมาชิก", "info"); const { error } = await createClient().from("members").update({ dog_count: dogCount, cat_count: catCount }).eq("id", memberId); if (error) return notify("บันทึกข้อมูลสัตว์เลี้ยงไม่สำเร็จ", "info"); setModal(null); notify("บันทึกจำนวนสัตว์เลี้ยงแล้ว"); }}>บันทึก</Button></Modal>
  <Modal open={modal === "password"} onClose={() => { setModal(null); setNewPassword(""); setConfirmPassword(""); }} title="เปลี่ยนรหัสผ่าน"><div className="space-y-4"><Field label="รหัสผ่านใหม่" hint="อย่างน้อย 8 ตัวอักษร"><Input type="password" minLength={8} autoComplete="new-password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></Field><Field label="ยืนยันรหัสผ่าน"><Input type="password" minLength={8} autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} /></Field><Button className="w-full" variant="primary" disabled={passwordSaving} onClick={async () => { if (newPassword.length < 8) return notify("รหัสผ่านใหม่ต้องมีอย่างน้อย 8 ตัวอักษร", "info"); if (newPassword !== confirmPassword) return notify("รหัสผ่านทั้งสองช่องไม่ตรงกัน", "info"); setPasswordSaving(true); const supabase = createClient(); const { error } = await supabase.auth.updateUser({ password: newPassword }); setPasswordSaving(false); if (error) return notify(`เปลี่ยนรหัสผ่านไม่สำเร็จ: ${error.message}`, "info"); setModal(null); setNewPassword(""); setConfirmPassword(""); notify("เปลี่ยนรหัสผ่านสำเร็จ กรุณาเข้าสู่ระบบอีกครั้ง"); await supabase.auth.signOut(); router.replace("/login"); router.refresh(); }}>{passwordSaving ? "กำลังเปลี่ยนรหัสผ่าน..." : "บันทึกรหัสผ่าน"}</Button></div></Modal>
  <ConfirmDialog open={Boolean(reward)} title="ยืนยันแลกของรางวัล" description={reward ? `กรุณาใช้สิทธิ์ที่หน้าร้าน และแสดงหน้านี้ให้พนักงานก่อนรับสินค้า ใช้ ${reward.points_cost.toLocaleString()} แต้ม เพื่อแลก “${reward.name}”` : ""} confirmLabel={redeeming ? "กำลังบันทึก..." : "ยืนยันแลก"} onClose={() => { if (!redeeming) setReward(null); }} onConfirm={redeemSelectedReward} />
  </main>;
}

function PageTitle({ title, subtitle }: { title: string; subtitle?: string }) { return <div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--brand-500)]">Tammy rewards</p><h1 className="mt-1 text-2xl font-black tracking-tight">{title}</h1></div>{subtitle ? <div className="flex shrink-0 items-center gap-2 rounded-2xl border border-amber-200 bg-gradient-to-br from-amber-50 to-orange-50 px-3.5 py-2.5 shadow-sm"><span className="grid h-8 w-8 place-items-center rounded-full bg-amber-400 text-white"><Star size={16} fill="currentColor"/></span><span><small className="block text-[10px] font-semibold text-stone-500">แต้มพร้อมใช้</small><b className="block text-sm text-amber-800">{subtitle.replace("คุณมี ", "")}</b></span></div> : null}</div>; }
function Section({ title, onAll, children }: { title: string; onAll: () => void; children: React.ReactNode }) { return <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="font-black">{title}</h2><button type="button" onClick={onAll} className="text-xs font-semibold text-[var(--brand-600)]">ดูทั้งหมด</button></div>{children}</section>; }
function Promo({ item, tone }: { item: News; tone: number }) { const backgrounds = ["bg-orange-50", "bg-emerald-50", "bg-violet-50"]; return <article className={`min-w-[225px] overflow-hidden rounded-2xl ${backgrounds[tone % backgrounds.length]}`}>{item.image_url ? <div className="relative aspect-square w-full bg-white/60"><Image unoptimized src={item.image_url} alt={item.title} fill sizes="225px" className="object-contain" /></div> : <div className="grid aspect-square place-items-center"><CatMark size={70} /></div>}<div className="p-4"><b className="block line-clamp-2">{item.title}</b><span className="mt-1 block text-sm text-[var(--brand-600)] line-clamp-2">{item.excerpt}</span></div></article>; }
function RewardCard({ item, index, onOpen }: { item: Reward; index: number; onOpen: () => void }) { return <button type="button" onClick={onOpen} className="surface overflow-hidden text-left transition hover:-translate-y-0.5 hover:shadow-[var(--shadow-lg)]"><div className={`relative aspect-square w-full overflow-hidden ${index % 2 ? "bg-emerald-50" : "bg-[var(--brand-50)]"}`}>{item.image_url ? <Image unoptimized src={item.image_url} alt={item.name} fill sizes="(max-width: 640px) 45vw, 190px" className="object-contain" /> : <span className="grid h-full place-items-center text-5xl">{item.category === "อาหาร" ? "🍪" : item.category === "คูปอง" ? "🎟️" : "🎁"}</span>}</div><div className="p-3"><span className="text-[10px] font-bold text-stone-400">{item.content_category || (item.category === "คูปอง" ? "คูปอง" : item.category)}</span><b className="mt-1 block line-clamp-2 text-sm">{item.name}</b><p className="mt-2 text-sm font-black text-[var(--brand-600)]">{item.points_cost.toLocaleString()} แต้ม</p><span className="mt-3 flex min-h-9 items-center justify-center rounded-[9px] bg-[var(--brand-500)] px-3 text-xs font-bold text-white">ดูรายละเอียด</span></div></button>; }

function RewardDetail({ item, points, onRedeem }: { item: Reward; points: number; onRedeem: () => void }) { return <div><div className="relative aspect-square overflow-hidden rounded-2xl bg-[var(--brand-50)]">{item.image_url ? <Image unoptimized src={item.image_url} alt={item.name} fill sizes="400px" className="object-contain" /> : <span className="grid h-full place-items-center text-7xl">🎁</span>}</div><div className="mt-4 flex items-center justify-between gap-3"><Badge>{item.content_category || (item.category === "คูปอง" ? "คูปอง" : item.category)}</Badge>{item.stock != null ? <span className="text-xs font-semibold text-emerald-600">คงเหลือ {item.stock} รายการ</span> : null}</div><h2 className="mt-3 text-xl font-black">{item.name}</h2><p className="mt-1 text-lg font-black text-[var(--brand-600)]">ใช้ {item.points_cost.toLocaleString()} แต้ม</p><p className="mt-4 text-sm leading-6 text-stone-600">{item.description}</p>{item.display_start ? <div className="mt-4 flex items-start gap-2 rounded-xl bg-stone-50 p-3 text-sm"><CalendarDays className="mt-0.5 shrink-0 text-stone-400" size={17} /><span>ใช้ได้ตั้งแต่ {customerThaiDate(item.display_start)}{item.display_end ? ` ถึง ${customerThaiDate(item.display_end)}` : ""}</span></div> : null}<div className="mt-5 border-t border-[var(--line)] pt-4"><h3 className="font-black">เงื่อนไขการแลก</h3><p className="mt-2 whitespace-pre-line text-sm leading-6 text-stone-600">{item.conditions || "ใช้สิทธิ์ที่หน้าร้านเท่านั้น และไม่สามารถแลกเปลี่ยนเป็นเงินสดได้"}</p></div><div className="mt-5 rounded-xl border border-amber-100 bg-amber-50 p-3 text-sm leading-6 text-amber-900">กรุณากดยืนยันเมื่ออยู่หน้าร้าน และแสดงหน้าจอให้พนักงานตรวจสอบ</div><Button className="mt-5 w-full" variant="primary" onClick={onRedeem} disabled={points < item.points_cost || item.stock === 0}>{item.stock === 0 ? "ของรางวัลหมด" : points < item.points_cost ? "แต้มไม่เพียงพอ" : "แลกรางวัล"}</Button></div>; }

function LoginPromoCarousel({ items, index, onClose, onPrevious, onNext, onDetails }: { items: News[]; index: number; onClose: (snoozeToday: boolean) => void; onPrevious: () => void; onNext: () => void; onDetails: () => void }) { const [snoozeToday, setSnoozeToday] = useState(false); const item = items[index]; return <div className="fixed inset-0 z-50 grid place-items-center bg-stone-950/50 p-4 backdrop-blur-sm"><section className="surface max-h-[calc(100dvh-32px)] w-full max-w-[330px] overflow-y-auto shadow-2xl soft-scroll"><div className="relative aspect-[4/3] bg-[var(--brand-50)]">{item.image_url ? <Image unoptimized src={item.image_url} alt={item.title} fill sizes="330px" className="object-contain p-2" /> : <span className="grid h-full place-items-center"><CatMark size={82} /></span>}<button type="button" onClick={() => onClose(snoozeToday)} aria-label="ปิด Popup" className="absolute right-3 top-3 grid h-8 w-8 place-items-center rounded-full bg-white/90 text-stone-600 shadow">×</button></div><div className="p-4"><Badge tone="brand">สิทธิพิเศษสำหรับคุณ</Badge><h2 className="mt-2 text-lg font-black">{item.title}</h2><p className="mt-1.5 line-clamp-3 text-sm leading-5 text-stone-500">{item.excerpt}</p><div className="mt-3 flex justify-center gap-1.5">{items.map((value, position) => <span key={value.id} className={`h-2 rounded-full ${position === index ? "w-5 bg-[var(--brand-500)]" : "w-2 bg-stone-200"}`} />)}</div><label className="mt-4 flex cursor-pointer items-center gap-2 rounded-xl bg-stone-50 px-3 py-2.5 text-xs font-semibold text-stone-600"><input type="checkbox" checked={snoozeToday} onChange={(event) => setSnoozeToday(event.target.checked)} className="h-4 w-4 accent-[var(--brand-500)]"/>ไม่แสดง Popup อีกในวันนี้</label><Button className="mt-3 w-full" variant="primary" onClick={onDetails}>ดูรายละเอียด</Button><div className="mt-2 grid grid-cols-2 gap-2"><Button size="sm" onClick={onPrevious} disabled={index === 0}>ก่อนหน้า</Button><Button size="sm" onClick={index === items.length - 1 ? () => onClose(snoozeToday) : onNext}>{index === items.length - 1 ? "ปิด" : "ถัดไป"}</Button></div></div></section></div>; }

function customerThaiDate(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString("th-TH", { day: "numeric", month: "short", year: "numeric" }); }
function localDateKey() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`; }
function normalizePointHistory(row: Record<string, unknown>): PointHistory { const value = Number(row.points_delta ?? row.points ?? row.amount ?? 0); const purchase = Number(row.purchase_amount ?? 0); const type = String(row.type ?? row.transaction_type ?? ""); const fallbackLabel = value >= 0 ? purchase > 0 ? `ได้รับจากยอดซื้อ ฿${purchase.toLocaleString()}` : "ได้รับแต้ม" : type.includes("redeem") ? "ใช้แต้มแลกรางวัล" : "ใช้แต้ม"; return { id: String(row.id ?? `${row.created_at}-${value}`), label: String(row.description ?? row.note ?? fallbackLabel), value, createdAt: String(row.created_at ?? new Date(0).toISOString()) }; }
function AccountButton({ icon, label, onClick, danger = false }: { icon: React.ReactNode; label: string; onClick: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-3 p-4 text-left text-sm font-semibold ${danger ? "text-red-600" : "hover:bg-stone-50"}`}>{icon}<span className="flex-1">{label}</span><ChevronRight size={16} className="text-stone-300" /></button>; }
function PetCounter({ icon, label, value, onChange }: { icon: React.ReactNode; label: string; value: number; onChange: (value: number) => void }) { return <div className="mt-3 flex items-center rounded-xl border border-[var(--line)] p-3"><span className="text-stone-500">{icon}</span><b className="ml-3 flex-1">{label}</b><Button size="sm" aria-label={`ลดจำนวน${label}`} onClick={() => onChange(Math.max(0, value - 1))}>−</Button><span className="w-10 text-center font-black">{value}</span><Button size="sm" aria-label={`เพิ่มจำนวน${label}`} onClick={() => onChange(value + 1)}>+</Button></div>; }
