"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Bell, Cat, ChevronLeft, ChevronRight, Dog, Gift, Home, LockKeyhole, Palette, Save, Star, UserRound } from "lucide-react";
import { CatMark } from "@/components/brand";
import { LoyaltyCard } from "@/components/loyalty-card";
import { ConfirmDialog, Modal, useFeedback } from "@/components/app-provider";
import { Badge, Button, Field, Input } from "@/components/ui";
import { createClient } from "@/lib/supabase/client";

type PageName = "หน้าหลัก" | "แต้ม" | "แลกรางวัล" | "บัญชี" | "ตกแต่งบัตร";
type Reward = { id: string; name: string; description: string; points_cost: number; category: string; image_url: string | null };
type News = { id: string; title: string; excerpt: string; image_url: string | null };
type Theme = { id: string; name: string; primary_color: string; secondary_color: string };
const fallbackRewards: Reward[] = [{ id: "1", name: "ขนมแมวเลีย 4 ชิ้น", description: "คละรส", points_cost: 500, category: "อาหาร", image_url: null }, { id: "2", name: "ชามอาหารสแตนเลส", description: "1 ใบ", points_cost: 400, category: "ของใช้", image_url: null }, { id: "3", name: "ไม้ตกแมว", description: "คละสี", points_cost: 600, category: "ของเล่น", image_url: null }];
const fallbackNews: News[] = [{ id: "1", title: "โปรพิเศษประจำเดือน", excerpt: "ลดสูงสุด 20%", image_url: null }, { id: "2", title: "สมาชิก Gold", excerpt: "รับแต้ม 2 เท่า", image_url: null }, { id: "3", title: "สินค้าใหม่", excerpt: "สำหรับน้องแมว", image_url: null }];
const baseColors = ["#ef4d43", "#f58a44", "#4d9b8d", "#7665a8", "#ed7194", "#477dd1"];

export default function CustomerPage() {
  const router = useRouter(); const { notify } = useFeedback();
  const [page, setPage] = useState<PageName>("หน้าหลัก"); const [points, setPoints] = useState(0); const [memberName, setMemberName] = useState("สมาชิก"); const [memberPhone, setMemberPhone] = useState(""); const [color, setColor] = useState(baseColors[0]); const [mascot, setMascot] = useState(0); const [dogCount, setDogCount] = useState(0); const [catCount, setCatCount] = useState(0);
  const [rewards, setRewards] = useState<Reward[]>(fallbackRewards); const [news, setNews] = useState<News[]>(fallbackNews); const [themes, setThemes] = useState<Theme[]>([]); const [reward, setReward] = useState<Reward | null>(null); const [modal, setModal] = useState<"notifications" | "news" | "pets" | "password" | null>(null);
  useEffect(() => { const supabase = createClient(); Promise.all([supabase.from("rewards").select("id,name,description,points_cost,category,image_url").eq("is_active", true), supabase.from("news_posts").select("id,title,excerpt,image_url").eq("is_published", true).order("publish_at", { ascending: false }), supabase.from("card_themes").select("id,name,primary_color,secondary_color").eq("is_active", true).order("sort_order"), supabase.auth.getUser()]).then(async ([rewardsResult, newsResult, themesResult, userResult]) => { if (rewardsResult.data) setRewards(rewardsResult.data as Reward[]); if (newsResult.data) setNews(newsResult.data as News[]); if (themesResult.data?.length) setThemes(themesResult.data as Theme[]); const user = userResult.data.user; if (!user) return; const { data: member } = await supabase.from("members").select("full_name,phone,points_balance,dog_count,cat_count").eq("auth_user_id", user.id).maybeSingle(); if (member) { setMemberName(member.full_name); setMemberPhone(member.phone); setPoints(member.points_balance); setDogCount(member.dog_count); setCatCount(member.cat_count); } }); }, []);
  const coupons = rewards.filter((item) => item.category === "คูปอง");
  const redeemableRewards = rewards.filter((item) => item.category !== "คูปอง");
  const navItems = [[Home, "หน้าหลัก"], [Star, "แต้ม"], [Gift, "แลกรางวัล"], [UserRound, "บัญชี"]] as const;
  function changePage(next: PageName) { setPage(next); window.scrollTo({ top: 0, behavior: "smooth" }); }
  return <main className="min-h-screen bg-[var(--canvas)] sm:p-6"><div className="mx-auto min-h-screen max-w-md overflow-hidden bg-white shadow-[var(--shadow-lg)] sm:min-h-[860px] sm:rounded-[32px] sm:border sm:border-[var(--line)]">
    <header className="sticky top-0 z-20 flex items-center border-b border-[var(--line)] bg-white/95 p-5 backdrop-blur"><span className="font-black text-[var(--brand-600)]">🐾 แทมมี่อาหารสัตว์</span><button type="button" aria-label="การแจ้งเตือน" onClick={() => setModal("notifications")} className="relative ml-auto grid h-10 w-10 place-items-center rounded-full hover:bg-stone-100"><Bell size={20} /><span className="absolute right-1 top-1 grid h-4 min-w-4 place-items-center rounded-full bg-[var(--brand-600)] px-1 text-[9px] font-black text-white">3</span></button></header>
    <div className="px-5 pb-28 pt-5">
      {page === "หน้าหลัก" ? <><p className="mb-3 text-stone-600">สวัสดี <b className="text-stone-900">{memberName}</b></p><LoyaltyCard color={color} points={points} /><Section title="ข่าวสาร" onAll={() => setModal("news")}><div className="flex gap-3 overflow-x-auto pb-2 soft-scroll">{news.slice(0, 3).map((item, index) => <Promo key={item.id} item={item} tone={index} />)}</div></Section>{coupons.length ? <Section title="คูปองสำหรับคุณ" onAll={() => changePage("แลกรางวัล")}><div className="grid grid-cols-2 gap-3">{coupons.slice(0, 2).map((item, index) => <RewardCard key={item.id} item={item} index={index} onExchange={() => setReward(item)} />)}</div></Section> : null}<Section title="ของรางวัลแนะนำ" onAll={() => changePage("แลกรางวัล")}><div className="grid grid-cols-2 gap-3">{redeemableRewards.slice(0, 2).map((item, index) => <RewardCard key={item.id} item={item} index={index} onExchange={() => setReward(item)} />)}</div></Section></> : null}
      {page === "แต้ม" ? <><PageTitle title="แต้มของฉัน" /><div className="surface mt-4 p-5"><p className="text-sm text-stone-500">แต้มคงเหลือ</p><b className="mt-1 block text-4xl tracking-tight">{points.toLocaleString()} <small className="text-sm">แต้ม</small></b><div className="mt-5 border-t border-[var(--line)] pt-4"><div className="flex justify-between"><b>Gold</b><span className="text-xs text-stone-400">อีก {Math.max(0, 3000 - points)} แต้ม</span></div><div className="mt-3 h-2 rounded-full bg-stone-100"><div className="h-full rounded-full bg-amber-400" style={{ width: `${Math.min(100, points / 30)}%` }} /></div></div></div><h2 className="mt-7 font-black">ประวัติแต้ม</h2><div className="mt-3 space-y-2">{[["ได้รับจากยอดซื้อ ฿1,200", "+12", "วันนี้ 14:32"], ["แลกขนมแมวเลีย", "-500", "2 ก.ย. 10:18"], ["ได้รับจากยอดซื้อ ฿800", "+8", "30 ส.ค. 09:12"]].map(([label, value, date]) => <div key={`${label}-${date}`} className="surface flex items-center p-4"><span className={`grid h-10 w-10 place-items-center rounded-xl ${value.startsWith("+") ? "bg-emerald-50 text-emerald-600" : "bg-red-50 text-red-500"}`}><Star size={18} /></span><span className="ml-3 flex-1"><b className="block text-sm">{label}</b><small className="text-stone-400">{date}</small></span><b className={value.startsWith("+") ? "text-emerald-600" : "text-red-500"}>{value}</b></div>)}</div></> : null}
      {page === "แลกรางวัล" ? <><PageTitle title="แลกของรางวัล" subtitle={`คุณมี ${points.toLocaleString()} แต้ม`} />{coupons.length ? <><h2 className="mt-5 font-black">คูปอง</h2><div className="mt-3 grid grid-cols-2 gap-3">{coupons.map((item, index) => <RewardCard key={item.id} item={item} index={index} onExchange={() => setReward(item)} />)}</div></> : null}<h2 className="mt-6 font-black">ของรางวัล</h2><div className="mt-3 grid grid-cols-2 gap-3">{redeemableRewards.map((item, index) => <RewardCard key={item.id} item={item} index={index} onExchange={() => setReward(item)} />)}</div></> : null}
      {page === "บัญชี" ? <><PageTitle title="บัญชีของฉัน" /><div className="surface mt-4 flex items-center p-4"><span className="grid h-12 w-12 place-items-center rounded-full bg-stone-100"><UserRound /></span><div className="ml-3"><b>{memberName}</b><p className="text-xs text-stone-400">{memberPhone || "ยังไม่ได้เข้าสู่ระบบ"}</p></div><Badge className="ml-auto">Gold</Badge></div><button type="button" onClick={() => changePage("ตกแต่งบัตร")} className="surface mt-4 flex w-full items-center p-4 text-left hover:border-[var(--brand-300)]"><Palette className="text-[var(--brand-600)]" /><span className="ml-3 flex-1 font-semibold">ตกแต่งบัตรสมาชิก</span><ChevronRight /></button><div className="surface mt-3 divide-y divide-[var(--line)]"><AccountButton icon={<UserRound size={18} />} label="ข้อมูลบัญชี" onClick={() => notify("ข้อมูลบัญชีเป็นปัจจุบันแล้ว")} /><AccountButton icon={<Dog size={18} />} label={`สัตว์เลี้ยง: สุนัข ${dogCount} · แมว ${catCount}`} onClick={() => setModal("pets")} /><AccountButton icon={<LockKeyhole size={18} />} label="เปลี่ยนรหัสผ่าน" onClick={() => setModal("password")} /><AccountButton icon={<ChevronRight size={18} />} label="ออกจากระบบ" danger onClick={async () => { await createClient().auth.signOut(); router.push("/login"); }} /></div></> : null}
      {page === "ตกแต่งบัตร" ? <><button type="button" onClick={() => changePage("บัญชี")} className="inline-flex items-center gap-1 text-sm font-semibold text-stone-500"><ChevronLeft size={17} />กลับ</button><PageTitle title="ตกแต่งบัตรสมาชิก" subtitle="เลือกจากสีและมาสคอตที่ร้านจัดเตรียมไว้" /><div className="mt-5"><LoyaltyCard color={color} /></div>{themes.length ? <><h2 className="mt-7 font-black">ธีมสำเร็จรูป</h2><div className="mt-3 grid gap-2">{themes.map((theme) => <button key={theme.id} type="button" onClick={() => setColor(theme.primary_color)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${color === theme.primary_color ? "border-[var(--brand-500)] bg-[var(--brand-50)]" : "border-[var(--line)]"}`}><span className="h-9 w-16 rounded-lg" style={{ background: `linear-gradient(135deg,${theme.primary_color},${theme.secondary_color})` }} /><b className="text-sm">{theme.name}</b></button>)}</div></> : null}<h2 className="mt-7 font-black">สีบัตร</h2><div className="mt-3 flex flex-wrap gap-3">{baseColors.map((item) => <button key={item} type="button" aria-label={`เลือกสี ${item}`} onClick={() => setColor(item)} className={`h-11 w-11 rounded-xl border-4 ${color === item ? "border-stone-800" : "border-white"}`} style={{ background: item }} />)}</div><h2 className="mt-7 font-black">มาสคอต</h2><div className="mt-3 grid grid-cols-3 gap-2">{["แมวโบกมือ", "แมวง่วงนอน", "แมวในสวน"].map((name, index) => <button type="button" key={name} onClick={() => setMascot(index)} className={`rounded-xl border p-3 text-center ${mascot === index ? "border-[var(--brand-500)] bg-[var(--brand-50)]" : "border-[var(--line)]"}`}><CatMark size={54} /><span className="mt-1 block text-xs">{name}</span></button>)}</div><Button className="mt-6 w-full" variant="primary" icon={<Save size={17} />} onClick={() => notify("บันทึกการตกแต่งบัตรแล้ว")}>บันทึกการตกแต่ง</Button></> : null}
    </div>
    <nav className="fixed bottom-0 left-1/2 z-20 grid w-full max-w-md -translate-x-1/2 grid-cols-4 border-t border-[var(--line)] bg-white/95 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] backdrop-blur sm:bottom-6 sm:rounded-b-[32px]">{navItems.map(([Icon, name]) => <button type="button" key={name} onClick={() => changePage(name)} className={`flex min-h-16 flex-col items-center justify-center gap-1 rounded-xl text-[11px] font-semibold ${page === name || (page === "ตกแต่งบัตร" && name === "บัญชี") ? "text-[var(--brand-600)]" : "text-stone-400 hover:bg-stone-50"}`}><Icon size={20} />{name}</button>)}</nav>
  </div>
  <Modal open={modal === "notifications"} onClose={() => setModal(null)} title="การแจ้งเตือน"><div className="space-y-2">{["คุณได้รับ 12 แต้มจากยอดซื้อล่าสุด", "Gold รับแต้ม 2 เท่าสัปดาห์นี้", "มีของรางวัลใหม่ให้แลก"].map((item) => <div key={item} className="rounded-xl bg-stone-50 p-3 text-sm">{item}</div>)}</div></Modal>
  <Modal open={modal === "news"} onClose={() => setModal(null)} title="ข่าวสารทั้งหมด"><div className="space-y-3">{news.map((item) => <div key={item.id} className="overflow-hidden rounded-2xl border border-[var(--line)]">{item.image_url ? <div className="relative aspect-square w-full bg-stone-50"><Image unoptimized src={item.image_url} alt={item.title} fill sizes="(max-width: 640px) 90vw, 460px" className="object-contain" /></div> : null}<div className="p-4"><b>{item.title}</b><p className="mt-1 text-sm text-stone-500">{item.excerpt}</p></div></div>)}</div></Modal>
  <Modal open={modal === "pets"} onClose={() => setModal(null)} title="จำนวนสัตว์เลี้ยง"><PetCounter icon={<Dog />} label="สุนัข" value={dogCount} onChange={setDogCount} /><PetCounter icon={<Cat />} label="แมว" value={catCount} onChange={setCatCount} /><Button className="mt-5 w-full" variant="primary" onClick={() => { setModal(null); notify("บันทึกจำนวนสัตว์เลี้ยงแล้ว"); }}>บันทึก</Button></Modal>
  <Modal open={modal === "password"} onClose={() => setModal(null)} title="เปลี่ยนรหัสผ่าน"><div className="space-y-4"><Field label="รหัสผ่านใหม่"><Input type="password" minLength={6} /></Field><Field label="ยืนยันรหัสผ่าน"><Input type="password" minLength={6} /></Field><Button className="w-full" variant="primary" onClick={() => { setModal(null); notify("เปลี่ยนรหัสผ่านแล้ว"); }}>บันทึกรหัสผ่าน</Button></div></Modal>
  <ConfirmDialog open={Boolean(reward)} title="ยืนยันแลกของรางวัล" description={reward ? `ใช้ ${reward.points_cost.toLocaleString()} แต้ม เพื่อแลก “${reward.name}”` : ""} confirmLabel="ยืนยันแลก" onClose={() => setReward(null)} onConfirm={() => { if (reward && points >= reward.points_cost) { setPoints((value) => value - reward.points_cost); notify("แลกของรางวัลสำเร็จ"); } else notify("แต้มไม่เพียงพอ", "info"); setReward(null); }} />
  </main>;
}

function PageTitle({ title, subtitle }: { title: string; subtitle?: string }) { return <div><h1 className="text-xl font-black">{title}</h1>{subtitle ? <p className="mt-1 text-sm text-stone-500">{subtitle}</p> : null}</div>; }
function Section({ title, onAll, children }: { title: string; onAll: () => void; children: React.ReactNode }) { return <section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="font-black">{title}</h2><button type="button" onClick={onAll} className="text-xs font-semibold text-[var(--brand-600)]">ดูทั้งหมด</button></div>{children}</section>; }
function Promo({ item, tone }: { item: News; tone: number }) { const backgrounds = ["bg-orange-50", "bg-emerald-50", "bg-violet-50"]; return <article className={`min-w-[225px] overflow-hidden rounded-2xl ${backgrounds[tone % backgrounds.length]}`}>{item.image_url ? <div className="relative aspect-square w-full bg-white/60"><Image unoptimized src={item.image_url} alt={item.title} fill sizes="225px" className="object-contain" /></div> : <div className="grid aspect-square place-items-center"><CatMark size={70} /></div>}<div className="p-4"><b className="block line-clamp-2">{item.title}</b><span className="mt-1 block text-sm text-[var(--brand-600)] line-clamp-2">{item.excerpt}</span></div></article>; }
function RewardCard({ item, index, onExchange }: { item: Reward; index: number; onExchange: () => void }) { return <article className="surface overflow-hidden"><div className={`relative aspect-square w-full overflow-hidden ${index % 2 ? "bg-emerald-50" : "bg-[var(--brand-50)]"}`}>{item.image_url ? <Image unoptimized src={item.image_url} alt={item.name} fill sizes="(max-width: 640px) 45vw, 190px" className="object-contain" /> : <span className="grid h-full place-items-center text-5xl">{item.category === "อาหาร" ? "🍪" : item.category === "คูปอง" ? "🎟️" : "🎁"}</span>}</div><div className="p-3"><b className="line-clamp-2 text-sm">{item.name}</b><p className="mt-2 text-sm font-black text-[var(--brand-600)]">{item.points_cost.toLocaleString()} แต้ม</p><Button className="mt-3 w-full" size="sm" variant="primary" onClick={onExchange}>แลก</Button></div></article>; }
function AccountButton({ icon, label, onClick, danger = false }: { icon: React.ReactNode; label: string; onClick: () => void; danger?: boolean }) { return <button type="button" onClick={onClick} className={`flex w-full items-center gap-3 p-4 text-left text-sm font-semibold ${danger ? "text-red-600" : "hover:bg-stone-50"}`}>{icon}<span className="flex-1">{label}</span><ChevronRight size={16} className="text-stone-300" /></button>; }
function PetCounter({ icon, label, value, onChange }: { icon: React.ReactNode; label: string; value: number; onChange: (value: number) => void }) { return <div className="mt-3 flex items-center rounded-xl border border-[var(--line)] p-3"><span className="text-stone-500">{icon}</span><b className="ml-3 flex-1">{label}</b><Button size="sm" aria-label={`ลดจำนวน${label}`} onClick={() => onChange(Math.max(0, value - 1))}>−</Button><span className="w-10 text-center font-black">{value}</span><Button size="sm" aria-label={`เพิ่มจำนวน${label}`} onClick={() => onChange(value + 1)}>+</Button></div>; }
